---
driver:
  name: docker

provisioner:
  name: itamae

platforms:
  - name: centos-6
    driver_config:
      image: centos:centos6

  - name: ubuntu-1404
    driver_config:
      image: ubuntu
      privileged: true

suites:
  - name: default
    run_list:
      - recipes/httpd/default.rb
