---
driver:
  name: docker

provisioner:
  name: itamae

platforms:
  - name: centos-6
    driver_config:
      image: centos:centos6
      require_chef_omnibus: false

suites:
  - name: default
    run_list:
      - recipes/httpd/default.rb
      - recipes/file/default.rb
